import os
import json
import torch
from pathlib import Path
from omegaconf import OmegaConf
from nemo.collections.asr.models import NeuralDiarizer

def main():
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    BASE_DIR = Path("experiments/phase13_karen_generalization")
    AUDIO_PATH = BASE_DIR / "audio" / "karen_normalized.wav"
    ORACLE_RTTM_PATH = BASE_DIR / "grounding" / "karen_oracle.rttm"
    MANIFEST_PATH = BASE_DIR / "manifests" / "karen_manifest.json"
    MSDD_OUT_DIR = BASE_DIR / "diarization" / "msdd_outputs"
    
    (BASE_DIR / "manifests").mkdir(exist_ok=True)
    MSDD_OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1. Create Manifest
    with open(MANIFEST_PATH, "w") as f:
        json.dump({
            "audio_filepath": str(AUDIO_PATH.absolute()),
            "offset": 0, 
            "duration": None, 
            "label": "infer", 
            "text": "-",
            "rttm_filepath": str(ORACLE_RTTM_PATH.absolute()),
        }, f)

    # 2. Configure MSDD
    config = OmegaConf.create({
        "diarizer": {
            "manifest_filepath": str(MANIFEST_PATH),
            "out_dir": str(MSDD_OUT_DIR),
            "oracle_vad": True, 
            "collar": 0.25, 
            "ignore_overlap": False,
            "vad": {"model_path": None, "external_vad_manifest": None, "parameters": {}},
            "speaker_embeddings": {
                "model_path": "titanet_large",
                "parameters": {
                    "window_length_in_sec": [1.5, 1.2, 1.0, 0.8, 0.5],
                    "shift_length_in_sec": [0.75, 0.6, 0.5, 0.4, 0.25],
                    "multiscale_weights": [1, 2, 3, 3, 3], 
                    "save_embeddings": True,
                },
            },
            "msdd_model": {
                "model_path": "diar_msdd_telephonic",
                "parameters": {
                    "use_backim_for_multiscale": True, 
                    "sigmoid_threshold": [0.7],
                    "use_adaptive_thres": False, 
                    "overlap_infer_spk_limit": 5,
                    "diar_window_length": 50, 
                    "infer_batch_size": 16,
                    "seq_eval_mode": False, 
                    "split_infer": True, 
                    "split_batch_size": 1,
                },
            },
            "clustering": {
                "parameters": {
                    "max_num_speakers": 10, 
                    "oracle_num_speakers": False, 
                    "max_rp_threshold": 0.25, 
                    "sparse_search_volume": 30
                },
            },
        },
        "batch_size": 16, 
        "num_workers": 1, 
        "sample_rate": 16000, 
        "verbose": True, 
        "device": DEVICE,
    })

    # 3. Run Diarization
    print("Running NeMo MSDD Diarization...")
    msdd_model = NeuralDiarizer(cfg=config).to(torch.device(DEVICE))
    msdd_model.diarize()
    
    # 4. Locate and report output
    rttm_dir = MSDD_OUT_DIR / "pred_rttms"
    rttm_files = list(rttm_dir.glob("*.rttm"))
    if not rttm_files:
        print("Error: No RTTM file generated by MSDD.")
        return

    # Copy/Symlink to the expected location
    final_rttm = BASE_DIR / "diarization" / "karen_msdd.rttm"
    import shutil
    shutil.copy(rttm_files[0], final_rttm)
    
    # Count speakers
    speakers = set()
    with open(final_rttm, "r") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) >= 8:
                speakers.add(parts[7])
    
    print(f"MSDD complete. Discovered Speaker Count: {len(speakers)}")
    print(f"RTTM saved to {final_rttm}")

if __name__ == "__main__":
    main()
